### ISSUE TITLE
[BUG] Unknown behaviour / code conflict?

### ISSUE THREAD

**Issue by redstrike** [adrianmay/rhaboo#16]
I just included the script, and rhaboo is conflicted with my mejs custom playlist. I have tried to clear all data in local storage, but no hope.

The bug happens at data-id from 27 to 30. My site works correctly after remove rhaboo.

![rhaboo_bug](https://cloud.githubusercontent.com/assets/2168227/5519773/571b7d56-8995-11e4-8954-293bc382d039.jpg)

**Comment by adrianmay** [comment]
Hi Tung,

I can reproduce your two errors:

A) Cannot read property 'shift' of undefined.
The undefined in this case is something called 'listClone' that you pulled out of store.js. Rhaboo is not supposed to interoperate with that library, but to replace it. I still get this error if I comment out the reference to rhaboo. So that's something you should ask store.js about if you choose that library. I think store.js would also ask you to use just one of rhaboo and store.js. Otherwise you have two hammers going for the same nail and should expect aggro.

B) 'undefined is not a function' in min.20150101_e2.js. 
I can confirm that this disappears if I comment out rhaboo, but it's minified so I don't know how to diagnose the problem. What is min.20150101_e2.js? Can you provide the non-minified version?

Adrian.

**Comment by redstrike** [comment]
Hi Adrian,

A) rhaboo was used before store.js, but after that bug I have to replaced it to continue working. After included store.js and tried to detect bugs, I didn't see any new errors. So I leave it there. Below is the code that use local storage (I swapped just one line to interchange rhaboo with store.js)

```javascript
var $mejs = $(getId('vn2rap-mejs-player'));
$mejs.html('');

// Get a clone of playlist in local storage
var listClone = locStor.playlist.slice(); // rhaboo code
var listClone = store.get('songs'), // store.js code

var listSongsHTML = '', s = null;

while (s = listClone.shift()) {
    listSongsHTML += '<source src="http://www.raphay.com/MEDIA' + s[3] + '" title="' + s[1] + ' - ' + s[2]+ '">'
}

$mejs.html(listSongsHTML); // then load mejs
```

B) min.js is the combination of store.js, jquery-2.1.1-custom-build, MBP-helper, our main js code. You could get it here: http://m.raphay.com/js/combined.js

Tung.

**Comment by adrianmay** [comment]
Hi Tung,

Now I uncommented your rhaboo lines and removed the reference to store.js and the redundant copy in combined.js. I no longer see error A. I'm still working on error B and will reply soon.  

Adrian.

**Comment by redstrike** [comment]
Hi Adrian,

I have modified some code in play playlist to test again, player is working with new code now but same bugs happen, I hope this can make it easier for you to detect the bug. I forgot to include the mejs source code, you could get it here: http://m.raphay.com/mejs/mediaelement-and-player.js

Tung.

**Comment by adrianmay** [comment]
Hi Tung,

I think I fixed it. Please re-test with the current version and let me know if it's fixed or not.

Thanks for the tip-off BTW. This was a general incompatibility with jQuery so you helped me a lot by pointing it out.

Adrian.

**Comment by redstrike** [comment]
Hi Adrian,

I have updated new version of rhaboo, those have gone. But still have an "undefined" at the end. Is this a normal behaviour?

![untitled 1](https://cloud.githubusercontent.com/assets/2168227/5623021/f837fec2-957e-11e4-9ce9-092fb9e5915d.jpg)

Tung.

**Comment by adrianmay** [comment]
I had to make several other fixes to your code. Specifically, you are including store.js both directly from your html and in combined.js. I didn't try getting store.js and rhaboo to coexist because they are for the same purpose. So to test rhaboo, please remove both inclusions of store.js. Then you'll get several errors where you access 'store' from store.js. That functionality needs to come into rhaboo. You report and 'undefined' but don't tell me what is undefined, so I can't be sure, but it could be a playlist you are pulling out of rhaboo without having inserted it. I could only see code where you populate a playlist in store.js. BTW, you can save a lot of time by using unminified versions throughout during this development stage.

**Comment by redstrike** [comment]
I removed store.js in html last time. But the one in combined.js is a must for current production serving, so I just want to do a quick test to make sure rhaboo is also ready for production too. At this time, I don't see any bug appear, therefore I asked "Is this a normal behaviour?", if that "hidden undefined at the last of array" is normal I could add a line of code to exclude it here:

```javascript
while (s = listClone.shift()) {
    listSongsHTML += '<source src="http://www.raphay.com/MEDIA' + s[3] + '" title="' + s[1] + ' - ' + s[2]+ '">'
}
```

In my point of view, store.js and rhaboo are 2 independent libraries. They should not conflict each other for just be included on the same page without using at the same time (I didn't use them at the same time). In my main logic code, you could see that I just want to store some song objects in "local storage" and take it out, it clearly that I don't force rhaboo to take data from "native data structure of local storage". Below is the code which I modified last time to easy do a test with rhaboo, you could see it at bottom of page:

```js
    var store;
    store = Rhaboo.persistent('VN2RAP');

    // Auto generate a playable playlist in rhaboo datastore
    if (store.playlist === undefined || store.playlist.length == 0) {

        store.write('playlist', []);

        var touliver = [37080,"Nắm Lấy Tay Anh","Touliver","/lofi_mp3/vietnam/rap/Touliver/Nam_Lay_Tay_Anh_-_Touliver.mp3"];

        for (var i = 0; i < 4; i++) {
            store.playlist.push(touliver);
        }
    }

    var $mejs = $(getId('vn2rap-mejs-player'));

    $mejs.html('');

    var listClone = store.playlist.slice();
    // Sideline: I wonder why we have to do a slice here, why just don't give me a copy of that array instead of the reference.
   // So I could write this line like this: "var listClone = store.playlist;" or "store.get('playlist')"

//                var listClone = store.get('songs'); // this line is for store.js

    var listSongsHTML = '', s = null;

    while (s = listClone.shift()) {
        listSongsHTML += '<source src="http://www.raphay.com/MEDIA' + s[3] + '" title="' + s[1] + ' - ' + s[2]+ '">'
    }

    $mejs.html(listSongsHTML);
```

BTW, if you can't find out any bug, I think we could close this bug here. I just need to add an if clause to exclude that "undefined", which is "hidden" at the last of rhaboo's returned array.

Thanks for your support, Adrian.
Tung.

**Comment by adrianmay** [comment]
Hi Tung,

One reason your rhaboo code is incompatible with store.js is that the latter defines something called store, so those names will clash. Another reason is that I haven't tested that combination because it's nonsensical to have two mechanisms doing the same thing with the same resource. I think store.js would take the same attitude.  They *might* be compatible, but neither library is likely to guarantee it.

I just found your undefined in that screenshot. Sorry, I hadn't noticed it before. That's normal.

As for that slice, it's completely up to you. Do you want a clone or do you want the original? More interestingly, you only have one song in your example because you didn't slice touliver. If you write store.playlist[2].write(2, "two liver") then all four songs will be affected because they're just references to the same thing. That is not true in store.js or any other such library, but it is true in rhaboo. Rhaboo is like JS itself in that respect. 

I'm closing this now cos there seems to be no more bug.

Adrian.
